### ISSUE TITLE
Scrape all the customer reviews

### ISSUE THREAD

**Issue by ankitjain28may** [ankitjain28may/ScrapeAmazon#1]

**Comment by uj00007** [comment]
the reviews are coming fine in the file that is being created for the reviews...so would u explain the issue in detail..?

**Comment by ankitjain28may** [comment]
Ya I know it works fine.. Bt suppose if there are 30 customer reviews so it only scrape max 8-9 customer reviews not all the 30 customer reviews that the issue..!
